---
title: "Class meetings"
---

## Links related to class meetings

\[[Attendance reporting form](https://forms.gle/3Qy98p8UHWiZ4BSGA)\] -- fill out once per class meeting.

\[[Drive folder for winter presentations](https://drive.google.com/drive/folders/1yeuKF0rFvqbR_XvfSSN1KEdC2dgfnbeE?usp=share_link)\] -- upload your slides and handouts here.

\[[Presentation review form](https://forms.gle/XG5Y2GG4AEhfwuiD7)\] -- fill out once per presentation.

## Week 1

-   *Comments:* teams should be scheduling their initial project meetings this week to take place during week 2.

-   *Monday meeting*: course overview \[[slides](slides/week1-intro.qmd)\]

-   *Class assignments:*

    -   read syllabus

    -   prepare a motivational statement and \[[submit](https://forms.gle/6MeNMfhxetzxBB7A9)\] by Friday 1/20 11:59pm PST

    -   prepare a team contract and submit signed copy by Friday 1/27 11:59pm PST \[upload to [Google drive](https://drive.google.com/drive/folders/1iDUbNlSIq7NlwUWcWOZkNMdO6B-ji5KK?usp=sharing)\]

## Week 2

***Note WEDNESDAY MEETING this week due to MLK Jr. Day***

-   *Comments:* re-read project abstract before your team meeting.

-   *Wednesday meeting:* student panel on past project experiences

## Week 3

*Comments:* teams should have data in hand this week; presentation schedule updated; contracts due Friday 1/27; see [meeting notes template](https://docs.google.com/document/d/1Gcnq5osybY0mLhqpffguQoVf76MD4Xl0gPPWWv-7weI/edit?usp=sharing)

-   *Monday meeting:* getting started and tips for success \[[slides](https://docs.google.com/presentation/d/1xAnI-zn-JYmTb5kPhq22oDuKcT4buvBbRFtpsyN2l_o/edit?usp=sharing)\]

-   In-class presentations to begin next week; should focus on project background, data, goals, and current/planned work

    -   format: 20min presentation + 10min discussion

    -   to prepare: 10-15 slides and 1-2 page handout 24h in advance

    -   \[[handout template](https://docs.google.com/document/d/1ra6-28dQKfS4HnsMP_j19qRGfrQngI_HpjZ6YxW9Chw/edit?usp=sharing)\] \[[evaluation rubric](https://docs.google.com/document/d/17xafDkkMzrOD2a9pFIVQainnRSCBvC-YMfaEYVzpses/edit?usp=sharing)\] \[[last year's presentations](https://drive.google.com/drive/folders/1Iw6PtIs_A6NUgItVcIqdHk4gvvN0_QVq?usp=share_link)\]

    -   *note* last year's presentations were all given at the end of the quarter and ran 10m shorter

## Week 4

*Comments:* HPC workshop scheduled for 2/22, details TBA; presentation schedule adjusted to accommodate workshop.

-   *Monday meeting:* Amgen \[[handout](https://docs.google.com/document/d/1ap15jalmGXZDL51xEbTPHqgcVxM121VS850zudl-StI/edit?usp=share_link)\] \[[slides](https://docs.google.com/presentation/d/1B4SibhPw-dhYM3pxkoVu_daT__lQOyVvmQ9huJp7WL4/edit?usp=share_link)\] Appfolio \[[handout](https://drive.google.com/file/d/18_21zxHMV1ZSd15UpL0SF31l9E_5-Pwi/view?usp=share_link)\] \[[slides](https://docs.google.com/presentation/d/1EwdRHRZtgp1GFiO_1A627ZHmwyUK7Nhk/edit?usp=share_link&ouid=109419302730749851192&rtpof=true&sd=true)\]

## Week 5

*Comments:* add your (full) meetings to \[[this calendar](https://calendar.google.com/calendar/u/0?cid=Y184OWUyZDg3YTYzOWVhNWU5NjI5Mzk3NjJmODYyYzBmNDkzYWM5OGFmNmY5MTUyNWJmZjU3YTUzYTA0YTUzNDI2QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20)\] (current meeting organizers have permissions); add your roles to the \[[project assignments spreadsheet](https://docs.google.com/spreadsheets/d/15Phz5o8-04SkD_t2ifgboxFSrOHvSlU4wGrTWUAKYrE/edit?usp=sharing)\].

-   *Monday meeting:* CCBER \[[slides](https://docs.google.com/presentation/d/1n3MOnrd65C8JbpVjSHxrvf5y1Fmqsjnz/edit?usp=share_link&ouid=109419302730749851192&rtpof=true&sd=true)\] \[[handout](https://drive.google.com/file/d/1tNrXyHL6H9g66RRs08S7A_tY-ps95DMv/view?usp=share_link)\]; Caves lab \[[slides](https://docs.google.com/presentation/d/1KJfDzZUWqBDZMyRZvMcGiHBFR6mLQjOSFwL4tgajoAw/edit?usp=share_link)\] \[[handout](https://docs.google.com/document/d/19Z2tGX4A0vSRx7fVUb7ly6CgHcRUsqN_nEIwtlUn8dY/edit?usp=share_link)\]
