---
title: "Welcome to Data Science Capstone"
subtitle: "PSTAT197B/CMPSC190DE Winter 2026"
author: "Dr Coburn"
institute: 'UCSB'
format: 
  revealjs:
    incremental: true
    footer: 'PSTAT197A/CMPSC190DD Winter 2026'
    logo: 'img/ucsbds_hex.png'
    slide-number: true
    # smaller: true
---

# Overview

## Capstone goals

-   make **original contributions** on your research topic;

-   develop **domain expertise** in your project area(s);

-   develop and practice **communicating research outcomes** to diverse audiences;

-   improve **collaboration and teamwork** skills;

-   advance your **career development**;

-   produce a strong **work sample** for your professional portfolio

## Course structure

-   1 weekly class meeting, on Tuesdays

-   1 weekly team meeting, scheduled at a time of your choice (suggest Thursdays, during class time; 2:00 - 3:00 PM)

-   optional but highly recommended: second team meeting or working session without advisors (suggest during your section time)

-   few class assignments each term:

    -   one short presentation

    -   mid-term peer review

    -   summative deliverable at end of term

## Expectations

-   weekly time commitment: 12h = 2-3h in meetings + 9-10h on projects

-   engage fully in project work, with some accountability:

    -   draft, sign, and adhere to a team contract

    -   take on one pre-defined organizational role in your team

    -   participate in peer reviews once per quarter

## Roles

You'll take on one of the following roles:

-   *spokesperson*

-   *meeting organizer*

-   *note-taker*

-   *repository and data manager*

-   for five-person teams, *equity manager*

-   for three-person teams, *meeting organizer* and *note-taker* combine

## Peer review

Each quarter you'll evaluate yourself/teammates on the extent to which you/they achieved the following:

1.  Attended, participated in, and contributed to project meetings
2.  Honored agreements specified in the team contract
3.  Fulfilled assigned team role
4.  Contributed fair share of work
5.  Cooperated with teammates
6.  Communicated clearly and respectfully with teammates
7.  Helped teammates when asked

## Class meetings

Class meetings will be run like a seminar: we'll rotate through the project teams, with two teams presenting each meeting.

-   \~30min available per team, but budget time for discussion

-   currently in alphabetical order, but can swap by mutual agreement

-   to prepare: 10-ish slides and 1-2 page handout

-   further guidelines TBA

## Assessments

-   attendance record and class assignments;

-   end-of-term advisor assessments of individual participation and contributions;

-   instructor assessments of in-class presentations and poster;

-   peer reviews and end-of-term individual reflections.

# Getting started

## Initial meetings {.smaller}

Schedule an initial meeting for week 2. Can recommend: Slack channel + \[[when2meet](https://www.when2meet.com/)\].

Suggested agenda:

-   introductions (15m):

    -   name, position/background, fun fact

    -   something exciting about the project

-   project intro (20m)

    -   have mentor tell you about the project in detail in their own words

    -   focus on the big picture, ask questions

-   data access and logistics (10m)

    -   make arrangements to access/obtain data

-   action items (10m)

    -   determine what actions will be taken before the next meeting

    -   assign responsibility for each action

## Assignments

-   ***Motivational statement*** due Friday 1/9 11:59pm PST. Take some time to write a paragraph or two in response to the following prompts:

    -   Why are you participating in the capstone? What attracted you to the opportunity in the first place and how does it relate to your goals for your undergraduate education?

    -   What do you hope to get out of the experience? Why is that important to you?

    -   Submit via [Google form](https://forms.gle/pkuv2n3s4iuvkNjg9)

-   ***Team contracts*** due Friday 1/16 11:59pm PST. See [template](https://docs.google.com/document/d/1UOuKzWgLneHoNrTmuL6UZp0uJ6DJVPLdEiEXnEefBJw/edit?usp=sharing).

    -   \[Upload signed copy to [Google drive](https://drive.google.com/drive/folders/1kEVxID498R7_FJkrflManic7qBJ_OU8G?usp=sharing)\]
